### ISSUE TITLE
Email notification on build failure

### ISSUE THREAD

**Issue by goeblj** [SAP/cloud-s4-sdk-pipeline#10]
Hi,

is it possible to add email notifications to the build pipeline in case of build failures?

Thanks
Jürgen

**Comment by jjtang1985** [comment]
Hi Jürgen,

thank you for your question.

Currently we are working on the this feature, and it will be released soon.
Please stay tuned;)

Best regards, Junjie

**Comment by kurzy** [comment]
Sending emails should now be possible. It is already in the master branch and can be used from there.

The configuration will be added to the configuration.md. It will be similar to:

### Post action configuration

#### sendNotifications

The `sendNotifications` post build action can be used to send notifications to project members in case of a unsuccessful build outcome.
By default, an email is sent to the list of users who committed a change since the last non-broken build. Additionally, a set of recipients can be defined that should always receive notifications.

| Property | Default Value | Description |
| --- | --- | --- |
| `enabled` | false | If set to `true`, notifications will be sent. |
| `skipFeatureBranches` | false | If set to `true`, notifications will only be sent for the productive branch as defined in the general configuration section. |
| `recipients` | | List of email adresses that should be notified in addition to the standard recipients. |

Example for `sendNotifications`: 
```
postActions:
  enabled: true
  skipFeatureBranches: true
  recipients:
    - ryan.architect@foobar.com
    - john.doe@foobar.com
```

postActions is on the same level as stages or steps.
