### ISSUE TITLE
fortifyExecuteScan project version not right

### ISSUE THREAD

**Issue by T1mey** [SAP/cloud-s4-sdk-pipeline#46]
In my pom.xml the version is specified this way

` <version>1.0-SNAPSHOT</version>`

The pipeline now tries to finf this project version via ssc api call. 

![image](https://user-images.githubusercontent.com/10464878/89882499-36a55080-dbc7-11ea-87e9-3f4e45742b6d.png)

The pipeline is now looking for a project version that is named "1". This is not right it must look for "1.0-SNAPSHOT".
Build fails. 

After creating a version named "1" the pipleine is finding it and continues.

**Comment by T1mey** [comment]
any update ?

**Comment by daniel-kurzynski** [comment]
Hi, 
sorry for the late reply. 
The versioning is based on the version schema. By default we only use the major version.
See also: https://sap.github.io/jenkins-library/steps/fortifyExecuteScan/#versioningmodel

You can change this behavior by configuring the step.

We have chosen "major" as default because thus it will not require a new version in fortify after any version change, especially when it is about automatic versioning. 

Hope that helps. 

Best regards,

Daniel
